### ISSUE TITLE
Compatibility with react native/expo

### ISSUE THREAD

**Issue by rjtubera** [simplifycom/simplify-android-sdk#3]
Hi, I would like to ask if this integration is compatible with react native using expo?

Thanks

**Comment by YazeedAsaad** [comment]
@rjtubera Did you Implement this using react native yet ? im currently working on a solution and saw your comment, if you have made something can you share it

**Comment by rjtubera** [comment]
@YazeedAsaad, i opted using webframes because of time. Thanks
